services:
  backend:
    container_name: notification_api
    build:
     context: .
     dockerfile: NewNotificationMicroservice.Web/Dockerfile
    restart: always
    volumes:
      - ./appsettings.json:/app/appsettings.json
    ports:
      - "3000:8080"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  database:
    image: postgres:latest
    container_name: local_pgdb_notif
    restart: unless-stopped
    env_file: ".env"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  local_pgdata:
  pgadmin-data: